### ISSUE TITLE
[Feature] Provide example for process reading (read_raw_into) in cpp

### ISSUE THREAD

**Issue by therockf** [memflow/memflow-cmake-example#2]
Hello,
I have been trying to use this in CPP for a day, but can't figure out how to use read_raw_into correctly.
With rust and with memflow-py I had no problems with it.

```
        uint64_t address = some address.......
	ProcessInstance<CBox<void>, CArc<void>> process;
        os.process_by_name("SomeProcess.exe", &process);
	CSliceMut<uint8_t> obj = CSliceMut<uint8_t>();
	process.read_raw_into(address, obj);
```

What is the correct way to use this? Could you provide an example?

I have been trying to simulate the read_addr64 Method from memflow project.

```
#[skip_func]
    fn read_addr64(&mut self, addr: Address) -> PartialResult<Address>
    where
        Self: Sized,
    {
        self.read::<u64>(addr).map_data(|d| d.into())
    }
```

**Comment by h33p** [comment]
The following should work:

```cpp
        uint64_t address = some address.......;
	int value;
	ProcessInstance<CBox<void>, CArc<void>> process;
        os.process_by_name("SomeProcess.exe", &process);
	CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
	process.read_raw_into(address, obj);
	printf("val: %d\n", value);
```

**Comment by therockf** [comment]
> The following should work:
> 
> ```c++
>         uint64_t address = some address.......;
> 	int value;
> 	ProcessInstance<CBox<void>, CArc<void>> process;
>         os.process_by_name("SomeProcess.exe", &process);
> 	CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
> 	process.read_raw_into(address, obj);
> 	printf("val: %d\n", value);
> ```

Tried that before, this isn't working...


```
error: no matching function for call to ‘CSliceMut<unsigned char>::CSliceMut(uint8_t*, long unsigned int)’
   56 |                                 CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
```

**Comment by h33p** [comment]
> > The following should work:
> > ```c++
> >         uint64_t address = some address.......;
> > 	int value;
> > 	ProcessInstance<CBox<void>, CArc<void>> process;
> >         os.process_by_name("SomeProcess.exe", &process);
> > 	CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
> > 	process.read_raw_into(address, obj);
> > 	printf("val: %d\n", value);
> > ```
> 
> Tried that before, this isn't working...
> 
> ```
> error: no matching function for call to ‘CSliceMut<unsigned char>::CSliceMut(uint8_t*, long unsigned int)’
>    56 |                                 CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
> ```

My bad, this should work:

```
CSliceMut<uint8_t> v((char *)&value, sizeof(value));
```

[godbolt](https://godbolt.org/z/c3eao11qP)

**Comment by therockf** [comment]
> > > The following should work:
> > > ```c++
> > >         uint64_t address = some address.......;
> > > 	int value;
> > > 	ProcessInstance<CBox<void>, CArc<void>> process;
> > >         os.process_by_name("SomeProcess.exe", &process);
> > > 	CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
> > > 	process.read_raw_into(address, obj);
> > > 	printf("val: %d\n", value);
> > > ```
> > 
> > 
> > Tried that before, this isn't working...
> > ```
> > error: no matching function for call to ‘CSliceMut<unsigned char>::CSliceMut(uint8_t*, long unsigned int)’
> >    56 |                                 CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((uint8_t *)&value, sizeof(int));
> > ```
> 
> My bad, this should work:
> 
> ```
> CSliceMut<uint8_t> v((char *)&value, sizeof(value));
> ```
> 
> [godbolt](https://godbolt.org/z/c3eao11qP)

```
uint64_t read_addr_64(uint64_t address, ProcessInstance<CBox<void>, CArc<void>> process) {
    uint64_t value;
	CSliceMut<uint8_t> obj = CSliceMut<uint8_t>((char *)&value, sizeof(uint64_t));
	process.read_raw_into(address, obj);
	printf("val: %d\n", value);
    return value;
}
```

Yep, just tried that, this is absolutely working!
